class URL:
    STELLAR_BURGERS = 'https://stellarburgers.nomoreparties.site/'
    LOGIN_ENDPOINT = 'login'
    FORGOT_PASSWORD_ENDPOINT = 'forgot-password'
    RESET_PASSWORD_ENDPOINT = 'reset-password'
    ACCOUNT_PROFILE_ENDPOINT = 'account/profile'
    ORDER_FEED_ENDPOINT = 'feed'
    CREATE_USER_ENDPOINT = 'api/auth/register'
    DELETE_USER_ENDPOINT = 'api/auth/user'
    AUTH_USER_ENDPOINT = 'api/auth/login'